# Generated by Django 2.0.2 on 2019-01-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bancavirtual',
            name='transaccion',
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='transaccion',
        ),
        migrations.RemoveField(
            model_name='cajeroautomatico',
            name='transaccion',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('soltero', 'Solter@'), ('casado', 'Casad@'), ('viudo', 'Viud@'), ('divorciado', 'Divorciad@'), ('unionLibre', 'Unión Libre')], default='soltero', max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], default='m', max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipoCuenta',
            field=models.CharField(choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorro'), ('nomina', 'Nómina'), ('valores', 'Valores')], default='ahorros', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('retiro', 'Retiro'), ('deposito', 'Depósito')], default='deposito', max_length=30),
        ),
        migrations.DeleteModel(
            name='BancaVirtual',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='CajeroAutomatico',
        ),
    ]
